# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Sequence

from PyQt5 import QtCore
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QPalette,QPixmap
from PyQt5.QtWidgets import QApplication, QGridLayout, QMainWindow, QWidget, QStyle

from utils import (MyFonts, MyLabel, MyPushButton, WindowGeometry,
                   setupQFontDataBase)

'''
  Config:
  - Normal Small Blind value
  - Normal Small Blind step
  - Normal Level Time period
  - Heads Up Small Blind value
  - Heads Up Small Blind step
  - Heads Up Level Time period
'''

class PokerTimerWindow(QMainWindow):
  def __init__(self,
               geometry : WindowGeometry = WindowGeometry.FHD,
               level_period_m : int = 12,
               small_blind_step : int = 100):
    super().__init__()
    # POKER
    self.level_period = [level_period_m, 0]
    self.m = level_period_m
    self.s = 0
    self.l = 1
    self.sb = small_blind_step
    self.sec_cnt = 0
    self.time_step_ms = 10
    # Setup the Window
    self.setup_window(geometry)

  def setup_window(self,
                   geometry : WindowGeometry = WindowGeometry.FHD,
                   bg_colour: str = "gray"):
    # QT
    self.setObjectName("MainWindow")
    self.resize(geometry)
    from pathlib import Path
    img = Path("dumb.jpg")
    self.setStyleSheet("#MainWindow { "
                       f" border-image: url({img.absolute()}) 0 0 0 0 stretch stretch;"
                       "}")
    self.gridLayout = QGridLayout(self)
    self.gridLayout.setObjectName("gridLayout")
    # QFontDataBase
    self.qfontdb = setupQFontDataBase()
    # QTWidgets
    ## Timer
    timer = QTimer(self.gridLayout)
    ## Labels
    self.timer_label = MyLabel("Timer", MyFonts.Timer)
    self.blinds_label = MyLabel("Blinds", MyFonts.Blinds)
    ## PushButtons
    self.pb_prev_level = MyPushButton("prev_lvl_pb")
    self.pb_next_lvl = MyPushButton("next_lvl_pb")
    self.pb_headsup = MyPushButton("headsup_pb")
    self.pb_reset = MyPushButton("reset_pb")

    # Add Widgets to Layout
    self.gridLayout.addWidget(self.timer_label, 0, 0, 1, 2)
    self.gridLayout.addWidget(self.blinds_label, 1, 0, 1, 2)
    self.gridLayout.addWidget(self.pb_prev_level, 2, 0, 1, 1)
    self.gridLayout.addWidget(self.pb_next_lvl, 2, 1, 1, 1)
    self.gridLayout.addWidget(self.pb_reset, 3, 0, 1, 1)
    self.gridLayout.addWidget(self.pb_headsup, 3, 1, 1, 1)

    self.retranslateUi() # change labels

    # Setup the Central Widget
    widget = QWidget()
    widget.setLayout(self.gridLayout)
    self.setCentralWidget(widget)

    QtCore.QMetaObject.connectSlotsByName(self)

    # Connect widgets to actions
    self.pb_next_lvl.clicked.connect(self.next_level_button_action) # type: ignore
    self.pb_prev_level.clicked.connect(self.prev_level_button_action) # type: ignore
    self.pb_headsup.clicked.connect(self.headsup_button_action) # type: ignore
    self.pb_reset.clicked.connect(self.reset_button_action)
    timer.timeout.connect(self.showTime)

    # Resize Event
    self.resizeEvent = self.customResizeEvent

    # Start timer
    timer.start(self.time_step_ms)

  # Event methods
  def customResizeEvent(self, event):
    self.updateFonts()

  # method called by timer
  def showTime(self):
    self.sec_cnt += self.time_step_ms
    if self.sec_cnt == 1000:
      self.sec_cnt = 0
      self.l, self.m, self.s = self.update_level_and_time(self.l, self.m, self.s)
    self.timer_label.setText(f"{self.m}{self.vanishing_comma(self.sec_cnt)}{self.s:02d}")
    self.blinds_label.setText(f"L{self.l} | {self.l * self.sb}/{self.l * self.sb * 2}")

  def vanishing_comma(self,
                      sec_cnt: int,
                      on_time: int = 100,
                      position: int = 300):
    if (sec_cnt > position) and (sec_cnt < (position + on_time)):
      return " "
    return ":"

  def update_level_and_time(self, l, m, s):
    if m == 0 and s == 0:
      return l+1, *self.level_period
    if s == 0:
      return l, m-1, 59
    return l, m, s-1

  # Actions
  def next_level_button_action(self):
    self.l += 1
    self.m, self.s = self.level_period

  def prev_level_button_action(self):
    if self.l != 1:
      self.l -= 1
    self.m, self.s = self.level_period

  def headsup_button_action(self):
    self.l = 1
    self.m, self.s = 10, 0
    self.sb = 1000

  def reset_button_action(self):
    self.l = 1
    self.m, self.s = self.level_period
    self.sb = 100

  def updateFonts(self, dividers : Sequence = [8,20,30]):
    # Calculate font sizes based on window width and height
    width = self.width()
    font_size_1 = int(width / dividers[0])
    font_size_2 = int(width / dividers[1])
    font_size_3 = int(width / dividers[2])

    # Update font sizes
    font = self.timer_label.font()
    font.setPointSize(font_size_1)
    self.timer_label.setFont(font)

    font = self.blinds_label.font()
    font.setPointSize(font_size_2)
    self.blinds_label.setFont(font)

    font = self.pb_next_lvl.font()
    font.setPointSize(font_size_3)
    self.pb_next_lvl.setFont(font)

    font = self.pb_prev_level.font()
    font.setPointSize(font_size_3)
    self.pb_prev_level.setFont(font)

    font = self.pb_headsup.font()
    font.setPointSize(font_size_3)
    self.pb_headsup.setFont(font)

    font = self.pb_reset.font()
    font.setPointSize(font_size_3)
    self.pb_reset.setFont(font)

  def retranslateUi(self):
    _translate = QtCore.QCoreApplication.translate
    self.setWindowTitle(_translate("MainWindow", "PokerTimer"))
    self.timer_label.setText(_translate("MainWindow", "TextLabel"))
    self.blinds_label.setText(_translate("MainWindow", "TextLabel"))
    self.pb_prev_level.setText(_translate("MainWindow", "<="))
    self.pb_next_lvl.setText(_translate("MainWindow", "=>"))
    self.pb_headsup.setText(_translate("MainWindow", "HeadsUp"))
    self.pb_reset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
  import sys

  # print(MyFonts.Timer.families())
  # print(MyFonts.Timer.family())
  from PyQt5.QtGui import QFont, QFontDatabase

  # # QFontDatabase.addApplicationFont("./fonts/ToonyLine.otf")
  # raise ValueError(QFontDatabase.families(QFontDatabase()))
  # exit()
  app = QApplication(sys.argv)
  ptw = PokerTimerWindow(geometry=WindowGeometry.VGA)
  ptw.show()
  sys.exit(app.exec_())
